defaults:
  - vodp_base
  - _self_

n_obs_steps: 3
image_shape: [3, 240, 320]
output_dir: "checkpoints/vodp_kuavo_task1_small_${train_dataset.demo}"
mixed_precision: "bf16"
train_batch_size: 4
gradient_accumulation_steps: 1
checkpointing_period: 10000

shape_meta:
  obs:
    observation.images.head_cam_h:
      shape: ${image_shape}
      type: rgb
    observation.images.wrist_cam_l:
      shape: ${image_shape}
      type: rgb
    observation.images.wrist_cam_r:
      shape: ${image_shape}
      type: rgb
    action:
      shape: [16]
      type: low_dim
  action:
    shape: [16]

model:
  obs_encoder:
    out_channels: 526
    rgb_key: ['observation.images.head_cam_h', 'observation.images.wrist_cam_l', 'observation.images.wrist_cam_r']
    state_key: 'observation.state'
    emvis_config:
      dim_2d: null
      dim_3d_keys: ['frame', 'global']
      load_vggt_heads: true
      load_vggt_pretrain: true
      vggt_model_path: pretrained/VGGT-1B/model.pt
      interpolate: 'bilinear'
      mlp_ratio: 1.0
      drop_p: 0.0
      ft_heads: []
      ft_layer_idx: []
      intermediate_layer_idx: [23]
      seq_as_view: False
      only_first_view: True
      injector_config:
        fuse_2d: True
        fuse_3d: False
        ffn_layer_num: 1
        dim_out: 1024
      model_adapter_config:
        target: ResNetAdapter
        shape_out: [1, 1]
        dim_out: 1024
        conv_num: 3
      mv_fuser_config: {}
  out_channels: 1040


