defaults:
  - vodp_base
  - _self_

# 1-frame 3D variant tuned for kuavo dual-arm RGB+state
n_obs_steps: 1
image_shape: [3, 480, 640]
output_dir: "checkpoints/vodp_kuavo_task1_${train_dataset.demo}"

shape_meta:
  obs:
    head_cam_h:
      shape: ${image_shape}
      type: rgb
    wrist_cam_l:
      shape: ${image_shape}
      type: rgb
    agent_pos:
      shape: [16]
      type: low_dim
  action:
    shape: [16]

horizon: 8
n_action_steps: 8
n_latency_steps: 0
obs_as_global_cond: True

model:
  obs_encoder:
    out_channels: 526
    emvis_config:
      dim_2d: null
      dim_3d_keys: ['frame', 'global']
      load_vggt_heads: true
      load_vggt_pretrain: true
      vggt_model_path: pretrained/VGGT-1B/model.pt
      interpolate: 'bilinear'
      mlp_ratio: 1.0
      drop_p: 0.0
      ft_heads: []
      ft_layer_idx: []
      intermediate_layer_idx: [23]
      seq_as_view: False
      only_first_view: True
      injector_config:
        fuse_2d: True
        fuse_3d: False
        ffn_layer_num: 1
        dim_out: 1024
      model_adapter_config:
        target: ResNetAdapter
        shape_out: [1, 1]
        dim_out: 1024
        conv_num: 3
      mv_fuser_config: {}
  out_channels: 1038


